import Header from "@/components/organisms/Header";
import "./globals.css";
import Provider from "@/HOC/Provider";

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

declare global {
 interface Window {
  google: any;
 }
}

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en">
   <body>
    <Provider>
     <Header />
     {children}
    </Provider>
   </body>
  </html>
 );
}
